# mirai文档: https://docs.mirai.mamoe.net

server:
  port: 9706

spring:
  main:
    banner-mode: console
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/little_kanade?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    hikari:
      maximumPoolSize: 20

  redis:
    # 使用的数据库索引
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 60000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 30
        # 连接池中的最大空闲连接
        max-idle: 15
        # 连接池中的最小空闲连接
        min-idle: 15

mybatis-plus:
  # mapper.xml文件扫描地址
  mapper-locations: classpath:/mappers/*.xml
  global-config:
    banner: false
    db-config:
      # 自增
      id-type: auto
      # 大写转下划线
      table-underline: true
      # 插入以及更新策略
      insert-strategy: not_null
      update-strategy: not_null
  configuration:
    # 数据库字段自动转成实体类字段
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback.xml
  level:
    root: INFO